### ISSUE TITLE
Copy paste event

### ISSUE THREAD

**Issue by AngularTx** [HstarComponents/ngx-ckeditor#12] opened 2018-03-31 10:49 UTC
I am using reactive form with the editor. 
The editor doesn't trigger value when copy pasting text. Only when entering manually , it triggers the text. 

I am using angular 5

**Comment by hstarorg** [comment] 2018-04-01 02:02
I update the demo page for pasting text, https://hstarcomponents.github.io/ngx-ckeditor/#/form.
I can't reproduce your question.
The demo page source code at: https://github.com/HstarComponents/ngx-ckeditor/tree/master/examples/pages/reactive-form-demo

**Comment by AngularTx** [comment] 2018-04-01 07:48
To be more precise..

When I copy the text from some other source , and paste the content in the
editor, below are two things that I observe.
1. Word/char count does not get updated , shows zero
2. The value change property doesn't trigger in the TS file

After the user adds/removed some text, the editor recognises the changes
and changes look fine, both word/char count and value update.


I want to know how this scenario can be handled?

**Comment by hstarorg** [comment] 2018-04-02 04:29
@AngularTx hi, I updated the demo, no those questions, please check your code.

**Comment by hstarorg** [comment] 2018-08-22 15:35
If you reproduce the question, you can reopen it. Now, I'll close the issue. thanks.

**Closed by hstarorg** 2018-08-22 15:35 UTC
